spring.application.name=grpc-server

spring.grpc.server.port=9090
spring.grpc.server.enabled=true

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=toor
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Run data.sql after Hibernate creates tables
spring.jpa.defer-datasource-initialization=true